gitRepo: ArcBlock/abtnode-docs
srcPath: src
categories:
  abtnode:
    basePath: /abtnode
    title: Abt Node
    link: /
    priority: 999
    sidebar:
      "null":
        - /
      Production Deployment:
        url: /production-deployment
        links:
          - /production-deployment/bind-domain-with-reverse-proxy-server
        locales:
          zh: "在生产环境中部署 ABT Node"
