gitRepo: ArcBlock/abtnode-docs
srcPath: src
categories:
  abtnode:
    basePath: /
    title: Blocklet Server
    link: /
    priority: 999
    sidebar:
      "null":
        - /
      Introduction:
        url: /introduction
        links:
          - /introduction/abtnode-overview
          - /introduction/abtnode-setup
          - /introduction/abtnode-access
        locales:
          zh: 节点入门
      Blocklet Store:
        url: /store
        links:
          - /store/what-is-store
          - /store/find-and-install
        locales:
          zh: 应用市场
      Blocklet Management:
        url: /blocklet
        links:
          - /blocklet/basic-operations
          - /blocklet/environments
        locales:
          zh: 应用管理
      Service Gateway:
        url: /router
        links:
          - /router/what-is-router
          - /router/basic-usage
          - /router/bind-domain-to-node
          - /router/bind-domain-and-ssl
          - /router/certificates-for-localhost
        locales:
          zh: 路由管理
      Logs:
        url: /logs
        links:
          - /logs/blocklet-logs
          - /logs/abtnode-logs
      Settings:
        url: /settings
        links :
          - /settings/basic
          - /settings/access-keys
          - /settings/integrations
      Deployment:
        url: /deployment
        links:
          - /deployment/best-practice
          - /deployment/from-aws-ami
          - /deployment/behind-reverse-proxy
          - /deployment/run-in-docker
        locales:
          zh: "生产环境指南"
      Misc:
        url: /misc
        links:
          - /misc/member-management
          - /misc/graphql-console
        locales:
          zh: "其他功能"
      Developer Guide:
        url: /developer
        links:
          - /developer/resources
          - /developer/config-dev-env
          - /developer/abtnode-cli
          - /developer/blocklet-cli
          - /developer/static-blocklets
          - /developer/dapp-blocklets
          - /developer/blocklet -spec
          - /developer/blocklet-sdk
          - /developer/auth-service
          - /developer/send-notification
          - /developer/did-connect
          - /developer/composable-blocklet
          - /developer/blocklet-hooks
          - /developer/bundle-blocklets
          - /developer/publish-blocklets
          - /developer/blocklet-registry
          - /developer/blocklet-codespaces
          - /developer/docker-registry
        locales:
          zh: 开发者指南
