gitRepo: ArcBlock/abtnode-docs
srcPath: src
categories:
  abtnode:
    basePath: /abtnode
    title: Abt Node
    link: /
    priority: 999
    sidebar:
      "null":
        - /
      Introduction:
        url: /introduction
        links:
          - /introduction/abtnode-overview
          - /introduction/how-to-get-abtnode
          - /introduction/setup-your-abt-node
        locales:
          zh: 节点入门
      Marketplace:
        url: /marketplace
        links:
          - /marketplace/find-and-install
          - /marketplace/upgrade-downgrade
        locales:
          zh: 应用市场
      Blocklets:
        url: /blocklet
        links:
          - /blocklet/basic-operations
          - /blocklet/environments
          - /blocklet/core-blocklets
        locales:
          zh: 应用管理
      Service Gateway:
        url: /router
        links:
          - /router/what-is-router
          - /router/basic-usage
          - /router/install-nginx
          - /router/certificates-for-localhost
        locales:
          zh: 路由管理
      Deployment:
        url: /deployment
        links:
          - /deployment/best-practice
          - /deployment/from-aws-ami
          - /deployment/behind-reverse-proxy
        locales:
          zh: "生产环境指南"
      Misc:
        url: /misc
        links:
          - /misc/node-settings
          - /misc/member-management
          - /misc/graphql-console
        locales:
          zh: "其他功能"
      Developer Guide:
        url: /developer
        links:
          - /developer/abtnode-cli
          - /developer/configuration
          - /developer/storage-structure
          - /developer/blocklet-spec
          - /developer/static-blocklets
          - /developer/dapp-blocklets
          - /developer/blocklet-hooks
          - /developer/bundle-blocklets
          - /developer/publish-blocklets
          - /developer/blocklet-registry
        locales:
          zh: 开发者指南
