gitRepo: ArcBlock/abtnode-docs
srcPath: src
categories:
  abtnode:
    basePath: /
    title: Blocklet Server
    link: /
    priority: 999
    sidebar:
      'null':
        - /
      Introduction:
        url: /introduction
        links:
          - /introduction/overview
          - /introduction/setup
          - /introduction/access
        locales:
          zh: 节点入门
      Blocklet Store:
        url: /store
        links:
          - /store/what-is-store
          - /store/find-and-install
        locales:
          zh: 应用市场
      Blocklet Management:
        url: /blocklet
        links:
          - /blocklet/basic-operations
          - /blocklet/domains-urls
          - /blocklet/components
          - /blocklet/members
          - /blocklet/passports
          - /blocklet/configuration
        locales:
          zh: 应用管理
      Log Viewer:
        url: /logs
        links:
          - /logs/server-logs
          - /logs/router-logs
          - /logs/blocklet-logs
      Team Management:
        url: /team
        links:
          - /team/members
          - /team/passports
        locales:
          zh: '其他功能'
      Settings:
        url: /settings
        links:
          - /settings/basic
          - /settings/router
          - /settings/access-keys
          - /settings/integrations
      DevOps Guide:
        url: /deployment
        links:
          - /deployment/best-practice
          - /deployment/from-aws-ami
          - /deployment/behind-reverse-proxy
          - /deployment/run-in-docker
        locales:
          zh: '节点部署指南'
      Developer Guide:
        url: /developer
        links:
          - /developer/resources
          - /developer/config-dev-env
          - /developer/abtnode-cli
          - /developer/blocklet-cli
          - /developer/static-blocklets
          - /developer/dapp-blocklets
          - /developer/blocklet -spec
          - /developer/blocklet-sdk
          - /developer/auth-service
          - /developer/send-notification
          - /developer/did-connect
          - /developer/composable-blocklet
          - /developer/blocklet-hooks
          - /developer/bundle-blocklets
          - /developer/publish-blocklets
          - /developer/blocklet-registry
          - /developer/blocklet-codespaces
          - /developer/docker-registry
        locales:
          zh: 应用开发者指南
